# Generated by Django 2.2.7 on 2020-06-12 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20200613_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('type_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('day', models.IntegerField(choices=[(None, ' --- Select Day --- '), (1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Faculty')),
                ('schedule_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.ScheduleType')),
            ],
        ),
        migrations.CreateModel(
            name='FacultyAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('availability', models.BooleanField(default=False)),
                ('availabilityMsg', models.TextField(blank=True, default='N/A')),
                ('faculty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Faculty')),
            ],
        ),
    ]
