# Generated by Django 3.0.5 on 2020-05-29 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200522_0123'),
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=30)),
                ('type_description', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='facultyavailability',
            name='faculty',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.Faculty'),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Faculty')),
                ('schedule_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.ScheduleType')),
            ],
        ),
    ]
