# Generated by Django 3.0.5 on 2020-05-21 20:23

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='position',
            field=models.CharField(default='N/A', max_length=255),
        ),
        migrations.AlterField(
            model_name='admin',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.content_file_admin),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.content_file_faculty),
        ),
        migrations.AlterField(
            model_name='student',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to=accounts.models.content_file_student),
        ),
    ]
