# Generated by Django 2.2.7 on 2020-06-12 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200522_0123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='gender',
            field=models.CharField(choices=[(None, ' --- Select Gender --- '), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='faculty',
            name='gender',
            field=models.CharField(choices=[(None, ' --- Select Gender --- '), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[(None, ' --- Select Gender --- '), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2),
        ),
    ]
