# Generated by Django 2.2.7 on 2020-06-12 19:14

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_auto_20200613_0014'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('meeting_duration', models.IntegerField(validators=[django.core.validators.MinValueValidator(10)])),
                ('meeting_status', models.CharField(choices=[('postpone', 'postpone'), ('approve', 'Approve'), ('postpone', 'Postponed'), ('cancel', 'Cancel'), ('re_scheduled', 'Re Schedule'), ('complete', 'Complete'), ('request', 'Request')], max_length=20)),
                ('initiate_time', models.TimeField(blank=True, default=datetime.datetime.now)),
                ('requester_type', models.CharField(choices=[('s', 'Student'), ('f', 'faculty')], max_length=2)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Faculty')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('meeting_duration', models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10)])),
                ('meeting_status', models.CharField(choices=[('message', 'message'), ('postpone', 'postpone'), ('approve', 'Approve'), ('postpone', 'Postponed'), ('cancel', 'Cancel'), ('re_scheduled', 'Re Schedule'), ('complete', 'Complete'), ('request', 'Request')], max_length=20)),
                ('initiate_time', models.TimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('detail_type', models.CharField(choices=[('r', 'requester'), ('f', 'faculty')], max_length=2)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.Meeting')),
            ],
        ),
    ]
