# Generated by Django 2.2.7 on 2020-06-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meeting',
            old_name='time',
            new_name='start_time',
        ),
        migrations.RenameField(
            model_name='meeting_detail',
            old_name='time',
            new_name='start_time',
        ),
        migrations.AddField(
            model_name='meeting',
            name='finish_time',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_status',
            field=models.CharField(choices=[('approve', 'Approve'), ('cancel', 'Cancel'), ('re_scheduled', 'Re Schedule'), ('complete', 'Complete'), ('request', 'Request')], max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting_detail',
            name='meeting_status',
            field=models.CharField(choices=[('message', 'message'), ('approve', 'Approve'), ('cancel', 'Cancel'), ('re_scheduled', 'Re Schedule'), ('complete', 'Complete'), ('request', 'Request')], max_length=20),
        ),
    ]
